[package]
name = "resx_hasher"
version = "0.1.0"
authors = ["darrexx <darx.dev@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
xml-rs = "0.8.1"
hex = "0.4.2"
walkdir = "2.3.1"
